package penguin: sdk;

interface types {
  resource session {
    write-response: func(body: list<u8>,end-of-stream: bool) -> result;
  }
}


world proxy-wasm {
  use types.{session};

  export init-plugin: func();
  export request-filter: func(session: borrow<session>) -> result<bool,string>;
}
